name: blob-storage
version: 0.1.0
github: "adrianadrianadrianadrianadrian/blob-storage"
license: BSD3
author: "Adrian Glouftsis"
maintainer: "a.glouftsis@outlook.com"
copyright: "2023 Adrian Glouftsis"

description: A package that provides the core functionality of Azure blob storage.

dependencies:
  - base >= 4.7 && < 5
  - lens
  - transformers
  - mtl
  - template-haskell
  - text
  - containers
  - bytestring
  - uuid
  - http-types
  - mime-types

library:
  source-dirs: src
  default-extensions:
    - ConstraintKinds
    - TemplateHaskell
    - FlexibleInstances
    - OverloadedStrings
    - GeneralizedNewtypeDeriving
