name: blob-storage-io
version: 0.1.0.0
github: "adrianadrianadrianadrianadrian/blob-storage"
license: BSD3
author: "Adrian Glouftsis"
maintainer: "a.glouftsis@outlook.com"
copyright: "2023 Adrian Glouftsis"

description: A package that provides an IO implementation for the 'blob-storage' core package.

dependencies:
  - base >= 4.7 && < 5
  - text
  - wreq
  - http-types
  - lens
  - bytestring
  - case-insensitive
  - time
  - cryptohash-sha256
  - base64-bytestring
  - containers
  - mtl
  - string-interpolate
  - xml-conduit
  - xml-lens
  - blob-storage

library:
  source-dirs: src
  default-extensions:
    - LambdaCase
    - OverloadedStrings
    - QuasiQuotes
