name: blob-storage

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Build Id
        run: echo "BUILD_ID=$(date +%Y%m%d%H%I%S)" >> $GITHUB_ENV

      - name: Docker login
        run: docker login -u adriang123 -p ${{ secrets.DOCKER_TOKEN }} docker.io

      - name: Build & Push Dependencies
        run: |
          docker pull adriang123/blob-storage-build || echo "Build not found."
          docker build --cache-from adriang123/blob-storage-build -f build.Dockerfile -t adriang123/blob-storage-build .
          docker push adriang123/blob-storage-build

      - name: Build Library
        run: |
          sed '/**\/*.hs/d' ./.dockerignore > tmp && mv tmp .dockerignore

          docker build \
            -f dist.Dockerfile \
            -t adriang123/blob-storage \
            -t adriang123/blob-storage:"$BUILD_ID" \
            --build-arg BUILDIMAGE=adriang123/blob-storage-build .

          docker push adriang123/blob-storage:"$BUILD_ID"

      - name: Upload Library
        if: github.ref == 'refs/heads/master'
        run: |
          HACKAGE_KEY=${{ secrets.HACKAGE_KEY }} docker run -t adriang123/blob-storage \
            sh -c 'cd blob-storage && stack upload . \
              && cd .. \
              && cd blob-storage-io && stack upload .'
